name: idb-request
ui: mocha-bdd
scripts:
  - lib/index.js
browsers:
  - name: firefox
    version: latest
  - name: chrome
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: latest
  - name: android
    version: latest
#  - name: iphone
#    version: latest
#  - name: ipad
#    version: latest
#  - name: opera
#    version: latest